"""add_email_auth

Revision ID: 0866186de4ae
Revises: 1f52e5e5a9b9
Create Date: 2026-05-26 15:51:20.497980

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0866186de4ae'
down_revision: Union[str, None] = '1f52e5e5a9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
