"""Add rarity and gray icon to achievements

Revision ID: 45bf085f80e4
Revises: 9c53603acec9
Create Date: 2026-06-04 01:47:54.956040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf085f80e4'
down_revision: Union[str, None] = '9c53603acec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('icon_gray_url', sa.String(length=512), nullable=True))
    op.add_column('achievements', sa.Column('rarity_percent', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'rarity_percent')
    op.drop_column('achievements', 'icon_gray_url')
    # ### end Alembic commands ###