"""Add expires_at to platform_connections

Revision ID: 9b2a8f1f1abf
Revises: 45bf085f80e4
Create Date: 2026-06-08 14:48:34.548534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2a8f1f1abf'
down_revision: Union[str, None] = '45bf085f80e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connections', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_connections', 'expires_at')
    # ### end Alembic commands ###